version: '3.1'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password # default USER is root

  wordpress:
    image: wordpress
    #build: ./wordpress
    volumes:
      - ./wp_data:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    depends_on:
       - db

volumes:
  wpdoc: